const Screens = {
  Login: 'Login',
  OTP: 'OTP',
  ForgotPassword: 'ForgotPassword',
  FirstTimeLogin: 'FirstTimeLogin',
  TwoFA: 'TwoFA',

  Unit: 'Unit',
  UnitHome: 'UnitHome',
  UnitBookings: 'UnitBookings',
  UnitAccount: 'UnitAccount',
  UnitBookingCode: 'UnitBookingCode',
  UnitBookPassenger: 'UnitBookPassenger',
  UnitBookRPL: 'UnitBookRPL',
  UnitFerryScheduledTimings: 'UnitFerryScheduledTimings',
  UnitFerryGuidelines: 'UnitFerryGuidelines',
  UnitServiceRating: 'UnitServiceRating',
  UnitBookFerry: 'SafBookFerry',
  UnitSelectVehicle: 'UnitSelectVehicle',
  UnitReviewBooking: 'UnitReviewBooking',
  UnitAnnouncements: 'UnitAnnouncements',
  UnitRecurring: 'UnitRecurring',
  UnitNotification: 'UnitNotification',

  Admin: 'Admin',
  AdminHome: 'AdminHome',
  AdminBookings: 'AdminBookings', 
  AdminBookingData: 'AdminBookingData',
  AdminAnnouncement: 'AdminAnnouncement',
  AdminAccount: 'AdminAccount',
  AdminCalendar: 'AdminCalendar',
  AdminFilter: 'AdminFilter',
  AdminFilterResults: 'AdminFilterResults',
  AdminSearch: 'AdminSearch',
  AdminBookingType: 'AdminBookingType',
  AdminSelectVehicle: 'AdminSelctVehicle',
  AdminBookFerry: 'AdminBookFerry', 
  AdminBookPassenger: 'AdminBookPassenger', 
  AdminBookRPL: 'AdminBookRPL',
  AdminReviewBooking: 'AdminReviewBooking',
  AdminRecurring: 'AdminRecurring',

  ServiceProvider: 'ServiceProvider',
  ServiceProviderHome: 'ServiceProviderHome',
  ServiceProviderBookingData: 'ServiceProviderBookingData',
  ServiceProviderCalendar: 'ServiceProviderCalendar',
  ServiceProviderSearch: 'ServiceProviderSearch',
  ServiceProviderFilter: 'ServiceProviderFilter',
  ServiceProviderFilteredResult: 'ServiceProviderFilteredResult',
  ServiceProviderScanQR: 'ServiceProviderScanQR',
  ServiceProviderScanResult: 'ServiceProviderScanResult',
  ServiceProviderAccount: 'ServiceProviderAccount',
  ServiceProviderAnnouncement: 'ServiceProviderAnnouncement',
  
  DutyPersonnel: 'DutyPersonnel',
  DutyPersonnelBookings: 'DutyPersonnelBookings',
  DutyPersonnelFilter: 'DutyPersonnelFilter',
  DutyPersonnelFilteredResults: 'DutyPersonnelFilteredResults',
  DutyPersonnelAccount: 'DutyPersonnelAccount',
  DutyPersonnelBookRPL: 'DutyPersonnelBookRPL',
  DutyPersonnelReviewBooking: 'DutyPersonnelReviewBooking',
  
}

export default Screens